/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/generate-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Obtener token para autenticación de usuario
         * @description Genera un token para la autenticación de usuario basado en las credenciales proporcionadas.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Domain.Controller.Private.Auth.GenerateUserTokenDto"];
                    "text/json": components["schemas"]["Domain.Controller.Private.Auth.GenerateUserTokenDto"];
                    "application/*+json": components["schemas"]["Domain.Controller.Private.Auth.GenerateUserTokenDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Private.Auth.GenerateTokenResponse"];
                        "application/json": components["schemas"]["Domain.Controller.Private.Auth.GenerateTokenResponse"];
                        "text/json": components["schemas"]["Domain.Controller.Private.Auth.GenerateTokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/user-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener información del usuario
         * @description Recupera información sobre el usuario autenticado basado en el token proporcionado. Este endpoint requiere un token Bearer válido en el encabezado Authorization.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Private.Auth.GetUserInfoResponse"];
                        "application/json": components["schemas"]["Domain.Controller.Private.Auth.GetUserInfoResponse"];
                        "text/json": components["schemas"]["Domain.Controller.Private.Auth.GetUserInfoResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/candidacy-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener una lista paginada de tipos de candidatura
         * @description Devuelve una lista paginada de todos los tipos de candidatura registrados en el sistema. Endpoint público, no requiere autenticación.
         */
        get: {
            parameters: {
                query?: {
                    Page?: number;
                    PageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Public.CandidacyType.GetPaginationResponse.Response"];
                        "application/json": components["schemas"]["Domain.Controller.Public.CandidacyType.GetPaginationResponse.Response"];
                        "text/json": components["schemas"]["Domain.Controller.Public.CandidacyType.GetPaginationResponse.Response"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.BadRequestResponse"];
                        "application/json": components["schemas"]["Domain.API.BadRequestResponse"];
                        "text/json": components["schemas"]["Domain.API.BadRequestResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidacy-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener información de un tipo de candidatura
         * @description Devuelve la información de un tipo de candidatura identificado por su id.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Private.CandidacyType.GetByIdResponse.Response"];
                        "application/json": components["schemas"]["Domain.Controller.Private.CandidacyType.GetByIdResponse.Response"];
                        "text/json": components["schemas"]["Domain.Controller.Private.CandidacyType.GetByIdResponse.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Editar información de tipo de candidatura
         * @description Actualiza parcialmente el nombre y/o posición de un tipo de candidatura. Valida que el nombre y la posición sean únicos entre los demás tipos existentes.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Domain.Controller.Private.CandidacyType.UpdateDto"];
                    "text/json": components["schemas"]["Domain.Controller.Private.CandidacyType.UpdateDto"];
                    "application/*+json": components["schemas"]["Domain.Controller.Private.CandidacyType.UpdateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.OkResponse"];
                        "application/json": components["schemas"]["Domain.API.OkResponse"];
                        "text/json": components["schemas"]["Domain.API.OkResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/candidacy-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener una lista de tipos de candidatura
         * @description Devuelve una lista de todos los tipos de candidatura registrados en el sistema.
         */
        get: {
            parameters: {
                query?: {
                    Page?: number;
                    PageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Private.CandidacyType.GetPaginationResponse.Response"];
                        "application/json": components["schemas"]["Domain.Controller.Private.CandidacyType.GetPaginationResponse.Response"];
                        "text/json": components["schemas"]["Domain.Controller.Private.CandidacyType.GetPaginationResponse.Response"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.BadRequestResponse"];
                        "application/json": components["schemas"]["Domain.API.BadRequestResponse"];
                        "text/json": components["schemas"]["Domain.API.BadRequestResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Agregar un nuevo tipo de candidatura
         * @description Crea un nuevo tipo de candidatura en el sistema. El nombre y la posición deben ser únicos (el nombre se compara sin distinción de mayúsculas/minúsculas ni espacios).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Domain.Controller.Private.CandidacyType.AddDto"];
                    "text/json": components["schemas"]["Domain.Controller.Private.CandidacyType.AddDto"];
                    "application/*+json": components["schemas"]["Domain.Controller.Private.CandidacyType.AddDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Private.CandidacyType.AddResponse"];
                        "application/json": components["schemas"]["Domain.Controller.Private.CandidacyType.AddResponse"];
                        "text/json": components["schemas"]["Domain.Controller.Private.CandidacyType.AddResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{filePath}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener un archivo multimedia.
         * @description Sirve el archivo en línea con el tipo de contenido (MIME) correspondiente. No fuerza descarga. Recomendado para mostrar imágenes directamente en el navegador. Acepta el path codificado en URL.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    filePath: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/download/{filePath}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Descargar un archivo multimedia.
         * @description Fuerza la descarga del archivo con Content-Disposition: attachment, usando el nombre real del archivo. Acepta el path codificado en URL.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    filePath: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/scrutinies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener información de un escrutinio.
         * @description Devuelve la información de un escrutinio junto con sus planchas y candidaturas. Solo retorna datos si el escrutinio está disponible para votar (estado ABIERTO y dentro de su rango de fechas).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Public.Scrutiny.GetByIdResponse.Response"];
                        "application/json": components["schemas"]["Domain.Controller.Public.Scrutiny.GetByIdResponse.Response"];
                        "text/json": components["schemas"]["Domain.Controller.Public.Scrutiny.GetByIdResponse.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/scrutinies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener una lista de escrutinios
         * @description Devuelve una lista de todos los escrutinios que esten abiertos para votar.
         */
        get: {
            parameters: {
                query?: {
                    FromDate?: string;
                    ToDate?: string;
                    Page?: number;
                    PageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Public.Scrutiny.GetPaginationResponse.Response"];
                        "application/json": components["schemas"]["Domain.Controller.Public.Scrutiny.GetPaginationResponse.Response"];
                        "text/json": components["schemas"]["Domain.Controller.Public.Scrutiny.GetPaginationResponse.Response"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.BadRequestResponse"];
                        "application/json": components["schemas"]["Domain.API.BadRequestResponse"];
                        "text/json": components["schemas"]["Domain.API.BadRequestResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/scrutinies/{id}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Votar por una plancha.
         * @description Registra el voto del estudiante autenticado por una plancha del escrutinio. Requiere autenticación con rol ESTUDIANTE. Valida que el escrutinio esté disponible para votar, que el usuario tenga un estudiante vinculado, que la plancha pertenezca al escrutinio y que el estudiante no haya votado previamente.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Domain.Controller.Public.Scrutiny.PostVoteBody"];
                    "text/json": components["schemas"]["Domain.Controller.Public.Scrutiny.PostVoteBody"];
                    "application/*+json": components["schemas"]["Domain.Controller.Public.Scrutiny.PostVoteBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.OkResponse"];
                        "application/json": components["schemas"]["Domain.API.OkResponse"];
                        "text/json": components["schemas"]["Domain.API.OkResponse"];
                    };
                };
            };
        };
        /**
         * Revocar voto.
         * @description Permite al estudiante autenticado revocar su voto en un escrutinio. Requiere autenticación con rol ESTUDIANTE. Valida que el escrutinio esté disponible para votar, que el usuario tenga un estudiante vinculado y que el estudiante haya votado previamente.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.OkResponse"];
                        "application/json": components["schemas"]["Domain.API.OkResponse"];
                        "text/json": components["schemas"]["Domain.API.OkResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/scrutinies/{id}/vote-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener estado del voto del estudiante.
         * @description Devuelve si el estudiante autenticado ha votado en el escrutinio y, en caso afirmativo, por cuál plancha votó. Requiere autenticación con rol ESTUDIANTE.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Public.Scrutiny.GetVoteStatusResponse.Response"];
                        "application/json": components["schemas"]["Domain.Controller.Public.Scrutiny.GetVoteStatusResponse.Response"];
                        "text/json": components["schemas"]["Domain.Controller.Public.Scrutiny.GetVoteStatusResponse.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scrutinies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener información de un escrutinio.
         * @description Devuelve la información de un escrutinio identificado por su id, incluyendo su estado y, si fue firmado, la URL del archivo de firma.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Private.Scrutiny.GetByIdResponse.Response"];
                        "application/json": components["schemas"]["Domain.Controller.Private.Scrutiny.GetByIdResponse.Response"];
                        "text/json": components["schemas"]["Domain.Controller.Private.Scrutiny.GetByIdResponse.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Eliminar un escrutinio
         * @description Elimina un escrutinio y todos sus datos relacionados (planchas, candidaturas, votos, firmas e imágenes). Solo se puede eliminar si el escrutinio está en estado PENDIENTE.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.OkResponse"];
                        "application/json": components["schemas"]["Domain.API.OkResponse"];
                        "text/json": components["schemas"]["Domain.API.OkResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Actualizar un escrutinio
         * @description Actualiza parcialmente los datos de un escrutinio existente. Solo se puede actualizar si el escrutinio se encuentra en estado PENDIENTE.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Domain.Controller.Private.Scrutiny.UpdateDto"];
                    "text/json": components["schemas"]["Domain.Controller.Private.Scrutiny.UpdateDto"];
                    "application/*+json": components["schemas"]["Domain.Controller.Private.Scrutiny.UpdateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.OkResponse"];
                        "application/json": components["schemas"]["Domain.API.OkResponse"];
                        "text/json": components["schemas"]["Domain.API.OkResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/scrutinies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener una lista paginada de escrutinios
         * @description Devuelve una lista paginada de escrutinios. Permite filtrar opcionalmente por estado (statusId), fecha de inicio desde (fromDate) y fecha de fin hasta (toDate).
         */
        get: {
            parameters: {
                query?: {
                    StatusId?: number;
                    FromDate?: string;
                    ToDate?: string;
                    Page?: number;
                    PageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Private.Scrutiny.GetPaginationResponse.Response"];
                        "application/json": components["schemas"]["Domain.Controller.Private.Scrutiny.GetPaginationResponse.Response"];
                        "text/json": components["schemas"]["Domain.Controller.Private.Scrutiny.GetPaginationResponse.Response"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.BadRequestResponse"];
                        "application/json": components["schemas"]["Domain.API.BadRequestResponse"];
                        "text/json": components["schemas"]["Domain.API.BadRequestResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Agregar un nuevo escrutinio
         * @description Crea un nuevo escrutinio en el sistema. El escrutinio se registra con estado PENDIENTE automáticamente.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Domain.Controller.Private.Scrutiny.AddDto"];
                    "text/json": components["schemas"]["Domain.Controller.Private.Scrutiny.AddDto"];
                    "application/*+json": components["schemas"]["Domain.Controller.Private.Scrutiny.AddDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Private.Scrutiny.AddResponse"];
                        "application/json": components["schemas"]["Domain.Controller.Private.Scrutiny.AddResponse"];
                        "text/json": components["schemas"]["Domain.Controller.Private.Scrutiny.AddResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scrutinies/{id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Actualizar imagen de portada de un escrutinio
         * @description Sube y establece la imagen de portada de un escrutinio. Reemplaza la imagen anterior si existía. Solo se permite cuando el escrutinio está en estado PENDIENTE.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Private.Scrutiny.UploadImageResponse"];
                        "application/json": components["schemas"]["Domain.Controller.Private.Scrutiny.UploadImageResponse"];
                        "text/json": components["schemas"]["Domain.Controller.Private.Scrutiny.UploadImageResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scrutinies/{id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Aperturar un escrutinio
         * @description Cambia el estado del escrutinio de PENDIENTE a ABIERTO. Requiere que el escrutinio tenga al menos 2 planchas registradas.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.OkResponse"];
                        "application/json": components["schemas"]["Domain.API.OkResponse"];
                        "text/json": components["schemas"]["Domain.API.OkResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/scrutinies/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cerrar un escrutinio
         * @description Cambia el estado del escrutinio de ABIERTO a CERRADO. Solo se puede cerrar si el escrutinio se encuentra en estado ABIERTO.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.OkResponse"];
                        "application/json": components["schemas"]["Domain.API.OkResponse"];
                        "text/json": components["schemas"]["Domain.API.OkResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scrutinies/{id}/sign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Firmar un escrutinio
         * @description Sube un archivo de firma y cambia el estado del escrutinio de CERRADO a FIRMADO. Acepta archivos .jpg, .png o .pdf con un tamaño máximo de 2 MB. Solo se puede firmar si el escrutinio está en estado CERRADO.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Private.Scrutiny.SignResponse"];
                        "application/json": components["schemas"]["Domain.Controller.Private.Scrutiny.SignResponse"];
                        "text/json": components["schemas"]["Domain.Controller.Private.Scrutiny.SignResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scrutinies/{id}/revert-to-open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Revertir escrutinio a estado ABIERTO
         * @description Cambia el estado del escrutinio de CERRADO a ABIERTO. Solo se puede revertir si el escrutinio está en estado CERRADO.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.OkResponse"];
                        "application/json": components["schemas"]["Domain.API.OkResponse"];
                        "text/json": components["schemas"]["Domain.API.OkResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/scrutinies/{id}/revert-to-pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Revertir escrutinio a estado PENDIENTE
         * @description Cambia el estado del escrutinio de ABIERTO a PENDIENTE. Esta acción eliminará todos los votos registrados en el escrutinio. Solo se puede revertir si el escrutinio está en estado ABIERTO.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.OkResponse"];
                        "application/json": components["schemas"]["Domain.API.OkResponse"];
                        "text/json": components["schemas"]["Domain.API.OkResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/scrutinies/{scrutinyId}/slates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener información de una plancha.
         * @description Devuelve la información de una plancha identificada por su id dentro de un escrutinio, incluyendo todas sus candidaturas con su tipo de candidatura.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scrutinyId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Private.ScrutinySlate.GetByIdResponse.Response"];
                        "application/json": components["schemas"]["Domain.Controller.Private.ScrutinySlate.GetByIdResponse.Response"];
                        "text/json": components["schemas"]["Domain.Controller.Private.ScrutinySlate.GetByIdResponse.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Eliminar una plancha
         * @description Elimina una plancha y todas sus candidaturas (con sus imágenes). Solo se puede eliminar si el escrutinio está en estado PENDIENTE.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scrutinyId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.OkResponse"];
                        "application/json": components["schemas"]["Domain.API.OkResponse"];
                        "text/json": components["schemas"]["Domain.API.OkResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Actualizar una plancha
         * @description Actualiza la posición de una plancha existente dentro de un escrutinio. Solo se puede modificar si el escrutinio está en estado PENDIENTE.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scrutinyId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Domain.Controller.Private.ScrutinySlate.UpdateDto"];
                    "text/json": components["schemas"]["Domain.Controller.Private.ScrutinySlate.UpdateDto"];
                    "application/*+json": components["schemas"]["Domain.Controller.Private.ScrutinySlate.UpdateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.OkResponse"];
                        "application/json": components["schemas"]["Domain.API.OkResponse"];
                        "text/json": components["schemas"]["Domain.API.OkResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/scrutinies/{scrutinyId}/slates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener una lista de planchas
         * @description Devuelve una lista de todas las planchas pertenecientes a un escrutinio.
         */
        get: {
            parameters: {
                query?: {
                    Page?: number;
                    PageSize?: number;
                };
                header?: never;
                path: {
                    scrutinyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Private.ScrutinySlate.GetPaginationResponse.Response"];
                        "application/json": components["schemas"]["Domain.Controller.Private.ScrutinySlate.GetPaginationResponse.Response"];
                        "text/json": components["schemas"]["Domain.Controller.Private.ScrutinySlate.GetPaginationResponse.Response"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.BadRequestResponse"];
                        "application/json": components["schemas"]["Domain.API.BadRequestResponse"];
                        "text/json": components["schemas"]["Domain.API.BadRequestResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Agregar una nueva plancha
         * @description Crea una nueva plancha en un escrutinio. La posición debe ser única dentro del escrutinio. Solo se puede agregar si el escrutinio está en estado PENDIENTE.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scrutinyId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Domain.Controller.Private.ScrutinySlate.AddDto"];
                    "text/json": components["schemas"]["Domain.Controller.Private.ScrutinySlate.AddDto"];
                    "application/*+json": components["schemas"]["Domain.Controller.Private.ScrutinySlate.AddDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Private.ScrutinySlate.AddResponse"];
                        "application/json": components["schemas"]["Domain.Controller.Private.ScrutinySlate.AddResponse"];
                        "text/json": components["schemas"]["Domain.Controller.Private.ScrutinySlate.AddResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scrutinies/{scrutinyId}/slates/{slateId}/candidacies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener información de una candidatura.
         * @description Devuelve la información de una candidatura identificada por su id dentro de una plancha, incluyendo el tipo de candidatura asociado.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scrutinyId: string;
                    slateId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Private.ScrutinySlateCandidacy.GetByIdResponse.Response"];
                        "application/json": components["schemas"]["Domain.Controller.Private.ScrutinySlateCandidacy.GetByIdResponse.Response"];
                        "text/json": components["schemas"]["Domain.Controller.Private.ScrutinySlateCandidacy.GetByIdResponse.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Eliminar una candidatura
         * @description Elimina una candidatura de una plancha en un escrutinio. Solo se permite si el escrutinio está en estado PENDIENTE. Si la candidatura tiene una imagen asociada, también se elimina.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scrutinyId: string;
                    slateId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.OkResponse"];
                        "application/json": components["schemas"]["Domain.API.OkResponse"];
                        "text/json": components["schemas"]["Domain.API.OkResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Actualizar una candidatura
         * @description Actualiza parcialmente una candidatura existente en una plancha. Solo se permite si el escrutinio está en estado PENDIENTE. Si se envía un nuevo tipo de candidatura, valida que exista.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scrutinyId: string;
                    slateId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Domain.Controller.Private.ScrutinySlateCandidacy.UpdateDto"];
                    "text/json": components["schemas"]["Domain.Controller.Private.ScrutinySlateCandidacy.UpdateDto"];
                    "application/*+json": components["schemas"]["Domain.Controller.Private.ScrutinySlateCandidacy.UpdateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.OkResponse"];
                        "application/json": components["schemas"]["Domain.API.OkResponse"];
                        "text/json": components["schemas"]["Domain.API.OkResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/scrutinies/{scrutinyId}/slates/{slateId}/candidacies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener una lista de candidaturas
         * @description Devuelve una lista de todas las candidaturas pertenecientes a una plancha de un escrutinio.
         */
        get: {
            parameters: {
                query?: {
                    Page?: number;
                    PageSize?: number;
                };
                header?: never;
                path: {
                    scrutinyId: string;
                    slateId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Private.ScrutinySlateCandidacy.GetPaginationResponse.Response"];
                        "application/json": components["schemas"]["Domain.Controller.Private.ScrutinySlateCandidacy.GetPaginationResponse.Response"];
                        "text/json": components["schemas"]["Domain.Controller.Private.ScrutinySlateCandidacy.GetPaginationResponse.Response"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.BadRequestResponse"];
                        "application/json": components["schemas"]["Domain.API.BadRequestResponse"];
                        "text/json": components["schemas"]["Domain.API.BadRequestResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Agregar una nueva candidatura
         * @description Crea una nueva candidatura en una plancha de un escrutinio. Valida que el escrutinio esté en estado PENDIENTE, que la plancha pertenezca al escrutinio y que el tipo de candidatura exista.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scrutinyId: string;
                    slateId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Domain.Controller.Private.ScrutinySlateCandidacy.AddDto"];
                    "text/json": components["schemas"]["Domain.Controller.Private.ScrutinySlateCandidacy.AddDto"];
                    "application/*+json": components["schemas"]["Domain.Controller.Private.ScrutinySlateCandidacy.AddDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Private.ScrutinySlateCandidacy.AddResponse"];
                        "application/json": components["schemas"]["Domain.Controller.Private.ScrutinySlateCandidacy.AddResponse"];
                        "text/json": components["schemas"]["Domain.Controller.Private.ScrutinySlateCandidacy.AddResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scrutinies/{scrutinyId}/slates/{slateId}/candidacies/{id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Actualizar imagen de una candidatura
         * @description Sube y establece la imagen de una candidatura. Reemplaza la imagen anterior si existía. Solo se permite cuando el escrutinio está en estado PENDIENTE.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scrutinyId: string;
                    slateId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Private.ScrutinySlateCandidacy.UploadImageResponse"];
                        "application/json": components["schemas"]["Domain.Controller.Private.ScrutinySlateCandidacy.UploadImageResponse"];
                        "text/json": components["schemas"]["Domain.Controller.Private.ScrutinySlateCandidacy.UploadImageResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scrutiny-statuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener estados de escrutinios.
         * @description Devuelve todos los estados posibles de los escrutinios.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.EnumResponse_Domain.Models.EScrutinyStatus"];
                        "application/json": components["schemas"]["Domain.API.EnumResponse_Domain.Models.EScrutinyStatus"];
                        "text/json": components["schemas"]["Domain.API.EnumResponse_Domain.Models.EScrutinyStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener información de un estudiante.
         * @description Devuelve la información de un estudiante identificado por su id, incluyendo su número de matrícula, nombre, apellido, estado de graduación y el id de usuario asociado si lo tiene.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Private.Student.GetByIdResponse.Response"];
                        "application/json": components["schemas"]["Domain.Controller.Private.Student.GetByIdResponse.Response"];
                        "text/json": components["schemas"]["Domain.Controller.Private.Student.GetByIdResponse.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Editar información de estudiante
         * @description Edita la información de un estudiante identificado por su id.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Domain.Controller.Private.Student.EditDto"];
                    "text/json": components["schemas"]["Domain.Controller.Private.Student.EditDto"];
                    "application/*+json": components["schemas"]["Domain.Controller.Private.Student.EditDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.OkResponse"];
                        "application/json": components["schemas"]["Domain.API.OkResponse"];
                        "text/json": components["schemas"]["Domain.API.OkResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener una lista de estudiantes
         * @description Devuelve una lista de todos los estudiantes registrados en el sistema.
         */
        get: {
            parameters: {
                query?: {
                    Page?: number;
                    PageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Private.Student.GetPaginationResponse.Response"];
                        "application/json": components["schemas"]["Domain.Controller.Private.Student.GetPaginationResponse.Response"];
                        "text/json": components["schemas"]["Domain.Controller.Private.Student.GetPaginationResponse.Response"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.BadRequestResponse"];
                        "application/json": components["schemas"]["Domain.API.BadRequestResponse"];
                        "text/json": components["schemas"]["Domain.API.BadRequestResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Agregar un nuevo estudiante
         * @description Crea un nuevo estudiante en el sistema. El número de matrícula se genera automáticamente. El estudiante se crea con el estado de graduado en falso.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Domain.Controller.Private.Student.AddDto"];
                    "text/json": components["schemas"]["Domain.Controller.Private.Student.AddDto"];
                    "application/*+json": components["schemas"]["Domain.Controller.Private.Student.AddDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Private.Student.AddResponse"];
                        "application/json": components["schemas"]["Domain.Controller.Private.Student.AddResponse"];
                        "text/json": components["schemas"]["Domain.Controller.Private.Student.AddResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener información de un usuario.
         * @description Devuelve la información de un usuario identificado por su id. Si el usuario tiene rol de estudiante, incluye el id del estudiante asociado.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Private.User.GetByIdResponse.Response"];
                        "application/json": components["schemas"]["Domain.Controller.Private.User.GetByIdResponse.Response"];
                        "text/json": components["schemas"]["Domain.Controller.Private.User.GetByIdResponse.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Actualizar un usuario
         * @description Actualiza parcialmente un usuario existente. Si se cambia el rol a ESTUDIANTE, vincula el estudiante indicado y adopta su número de matrícula como nombre de usuario. Si el rol anterior era ESTUDIANTE y cambia a otro, desvincula al estudiante previo. Valida unicidad de nombre de usuario y existencia del estudiante si aplica.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Domain.Controller.Private.User.UpdateDto"];
                    "text/json": components["schemas"]["Domain.Controller.Private.User.UpdateDto"];
                    "application/*+json": components["schemas"]["Domain.Controller.Private.User.UpdateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.OkResponse"];
                        "application/json": components["schemas"]["Domain.API.OkResponse"];
                        "text/json": components["schemas"]["Domain.API.OkResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener una lista paginada de usuarios
         * @description Devuelve una lista paginada de usuarios registrados en el sistema, incluyendo su rol y estado activo.
         */
        get: {
            parameters: {
                query?: {
                    Page?: number;
                    PageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Private.User.GetPaginationResponse.Response"];
                        "application/json": components["schemas"]["Domain.Controller.Private.User.GetPaginationResponse.Response"];
                        "text/json": components["schemas"]["Domain.Controller.Private.User.GetPaginationResponse.Response"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.BadRequestResponse"];
                        "application/json": components["schemas"]["Domain.API.BadRequestResponse"];
                        "text/json": components["schemas"]["Domain.API.BadRequestResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Agregar un nuevo usuario
         * @description Crea un nuevo usuario en el sistema. Si el rol es ESTUDIANTE, debe enviarse el id del estudiante y el nombre de usuario se establece automáticamente con el número de matrícula. Valida que el rol exista, que el nombre de usuario sea único y, si aplica, que el estudiante exista y no tenga usuario asignado.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Domain.Controller.Private.User.AddDto"];
                    "text/json": components["schemas"]["Domain.Controller.Private.User.AddDto"];
                    "application/*+json": components["schemas"]["Domain.Controller.Private.User.AddDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.Controller.Private.User.AddResponse"];
                        "application/json": components["schemas"]["Domain.Controller.Private.User.AddResponse"];
                        "text/json": components["schemas"]["Domain.Controller.Private.User.AddResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user-roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener roles de usuarios.
         * @description Devuelve todos los roles de usuarios permitidos en el sistema.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Domain.API.EnumResponse_Domain.Models.EUserRole"];
                        "application/json": components["schemas"]["Domain.API.EnumResponse_Domain.Models.EUserRole"];
                        "text/json": components["schemas"]["Domain.API.EnumResponse_Domain.Models.EUserRole"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Domain.API.BadRequestResponse": {
            readonly ok?: boolean;
            badMessage: string | null;
        };
        "Domain.API.DataResponse_Domain.Models.EScrutinyStatus": {
            value: components["schemas"]["Domain.Models.EScrutinyStatus"];
            name: string | null;
        };
        "Domain.API.DataResponse_Domain.Models.EUserRole": {
            value: components["schemas"]["Domain.Models.EUserRole"];
            name: string | null;
        };
        "Domain.API.EnumResponse_Domain.Models.EScrutinyStatus": {
            ok: boolean;
            data: components["schemas"]["Domain.API.DataResponse_Domain.Models.EScrutinyStatus"][] | null;
        };
        "Domain.API.EnumResponse_Domain.Models.EUserRole": {
            ok: boolean;
            data: components["schemas"]["Domain.API.DataResponse_Domain.Models.EUserRole"][] | null;
        };
        "Domain.API.Interfaces.IPagination": {
            /** Format: int32 */
            pages?: number;
            /** Format: int32 */
            records?: number;
            /** Format: int32 */
            currentPage?: number;
            /** Format: int32 */
            prevPage?: number;
            /** Format: int32 */
            nextPage?: number;
        };
        "Domain.API.OkResponse": {
            ok?: boolean;
        };
        "Domain.Controller.Private.Auth.GenerateTokenResponse": {
            token: string | null;
        };
        "Domain.Controller.Private.Auth.GenerateUserTokenDto": {
            userName: string | null;
            password: string | null;
        };
        "Domain.Controller.Private.Auth.GetUserInfoResponse": {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            studentId: string | null;
            userName: string | null;
            userRole: components["schemas"]["Domain.Controller.Private.Auth.GetUserInfoResponse.Role"];
        };
        "Domain.Controller.Private.Auth.GetUserInfoResponse.Role": {
            /** Format: int32 */
            id: number;
            name: string | null;
        };
        "Domain.Controller.Private.CandidacyType.AddDto": {
            name: string | null;
            /** Format: int32 */
            position: number;
        };
        "Domain.Controller.Private.CandidacyType.AddResponse": {
            /** Format: int32 */
            id: number;
        };
        "Domain.Controller.Private.CandidacyType.GetByIdResponse.Data": {
            /** Format: int32 */
            id: number;
            name: string | null;
            /** Format: int32 */
            position: number;
        };
        "Domain.Controller.Private.CandidacyType.GetByIdResponse.Response": {
            ok?: boolean;
            data?: components["schemas"]["Domain.Controller.Private.CandidacyType.GetByIdResponse.Data"];
        };
        "Domain.Controller.Private.CandidacyType.GetPaginationResponse.Data": {
            /** Format: int32 */
            id: number;
            name: string | null;
            /** Format: int32 */
            position: number;
        };
        "Domain.Controller.Private.CandidacyType.GetPaginationResponse.Response": {
            ok?: boolean;
            pagination: components["schemas"]["Domain.API.Interfaces.IPagination"];
            data: components["schemas"]["Domain.Controller.Private.CandidacyType.GetPaginationResponse.Data"][] | null;
        };
        "Domain.Controller.Private.CandidacyType.UpdateDto": {
            name?: string | null;
            /** Format: int32 */
            position?: number | null;
        };
        "Domain.Controller.Private.Scrutiny.AddDto": {
            title: string | null;
            description: string | null;
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate: string;
        };
        "Domain.Controller.Private.Scrutiny.AddResponse": {
            /** Format: uuid */
            id: string;
        };
        "Domain.Controller.Private.Scrutiny.GetByIdResponse.Data": {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            statusId: number;
            status: components["schemas"]["Domain.Controller.Private.Scrutiny.GetByIdResponse.StatusData"];
            title: string | null;
            description: string | null;
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate: string;
            imageUrl?: string | null;
            signFileUrl?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string | null;
        };
        "Domain.Controller.Private.Scrutiny.GetByIdResponse.Response": {
            ok?: boolean;
            data?: components["schemas"]["Domain.Controller.Private.Scrutiny.GetByIdResponse.Data"];
        };
        "Domain.Controller.Private.Scrutiny.GetByIdResponse.StatusData": {
            /** Format: int32 */
            id: number;
            name: string | null;
        };
        "Domain.Controller.Private.Scrutiny.GetPaginationResponse.Data": {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            statusId: number;
            title: string | null;
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate: string;
            imageUrl?: string | null;
        };
        "Domain.Controller.Private.Scrutiny.GetPaginationResponse.Response": {
            ok?: boolean;
            pagination: components["schemas"]["Domain.API.Interfaces.IPagination"];
            data: components["schemas"]["Domain.Controller.Private.Scrutiny.GetPaginationResponse.Data"][] | null;
        };
        "Domain.Controller.Private.Scrutiny.SignResponse": {
            fileUrl: string | null;
        };
        "Domain.Controller.Private.Scrutiny.UpdateDto": {
            title?: string | null;
            description?: string | null;
            /** Format: date-time */
            startDate?: string | null;
            /** Format: date-time */
            endDate?: string | null;
        };
        "Domain.Controller.Private.Scrutiny.UploadImageResponse": {
            imageUrl: string | null;
        };
        "Domain.Controller.Private.ScrutinySlate.AddDto": {
            /** Format: int32 */
            position: number;
        };
        "Domain.Controller.Private.ScrutinySlate.AddResponse": {
            /** Format: uuid */
            id: string;
        };
        "Domain.Controller.Private.ScrutinySlate.GetByIdResponse.CandidacyData": {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            scrutinyId: string;
            /** Format: uuid */
            slateId: string;
            /** Format: int32 */
            candidacyTypeId: number;
            name: string | null;
            lastName: string | null;
            imageUrl?: string | null;
            candidacyType: components["schemas"]["Domain.Controller.Private.ScrutinySlate.GetByIdResponse.CandidacyTypeData"];
        };
        "Domain.Controller.Private.ScrutinySlate.GetByIdResponse.CandidacyTypeData": {
            /** Format: int32 */
            id: number;
            name: string | null;
        };
        "Domain.Controller.Private.ScrutinySlate.GetByIdResponse.Data": {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            scrutinyId: string;
            /** Format: int32 */
            position: number;
            candidacies: components["schemas"]["Domain.Controller.Private.ScrutinySlate.GetByIdResponse.CandidacyData"][] | null;
        };
        "Domain.Controller.Private.ScrutinySlate.GetByIdResponse.Response": {
            ok?: boolean;
            data?: components["schemas"]["Domain.Controller.Private.ScrutinySlate.GetByIdResponse.Data"];
        };
        "Domain.Controller.Private.ScrutinySlate.GetPaginationResponse.Data": {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            scrutinyId: string;
            /** Format: int32 */
            position: number;
            /** Format: int32 */
            countCandidacies: number;
            firstCandidacy?: components["schemas"]["Domain.Controller.Private.ScrutinySlate.GetPaginationResponse.FirstCandidacyData"];
        };
        "Domain.Controller.Private.ScrutinySlate.GetPaginationResponse.FirstCandidacyData": {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            scrutinyId: string;
            /** Format: uuid */
            slateId: string;
            /** Format: int32 */
            candidacyTypeId: number;
            name: string | null;
            lastName: string | null;
        };
        "Domain.Controller.Private.ScrutinySlate.GetPaginationResponse.Response": {
            ok?: boolean;
            pagination: components["schemas"]["Domain.API.Interfaces.IPagination"];
            data: components["schemas"]["Domain.Controller.Private.ScrutinySlate.GetPaginationResponse.Data"][] | null;
        };
        "Domain.Controller.Private.ScrutinySlate.UpdateDto": {
            /** Format: int32 */
            position?: number | null;
        };
        "Domain.Controller.Private.ScrutinySlateCandidacy.AddDto": {
            /** Format: int32 */
            candidacyTypeId: number;
            name: string | null;
            lastName: string | null;
        };
        "Domain.Controller.Private.ScrutinySlateCandidacy.AddResponse": {
            /** Format: uuid */
            id: string;
        };
        "Domain.Controller.Private.ScrutinySlateCandidacy.GetByIdResponse.CandidacyTypeData": {
            /** Format: int32 */
            id: number;
            name: string | null;
        };
        "Domain.Controller.Private.ScrutinySlateCandidacy.GetByIdResponse.Data": {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            scrutinyId: string;
            /** Format: uuid */
            slateId: string;
            /** Format: int32 */
            candidacyTypeId: number;
            name: string | null;
            lastName: string | null;
            imageUrl?: string | null;
            candidacyType: components["schemas"]["Domain.Controller.Private.ScrutinySlateCandidacy.GetByIdResponse.CandidacyTypeData"];
        };
        "Domain.Controller.Private.ScrutinySlateCandidacy.GetByIdResponse.Response": {
            ok?: boolean;
            data?: components["schemas"]["Domain.Controller.Private.ScrutinySlateCandidacy.GetByIdResponse.Data"];
        };
        "Domain.Controller.Private.ScrutinySlateCandidacy.GetPaginationResponse.Data": {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            scrutinyId: string;
            /** Format: uuid */
            slateId: string;
            /** Format: int32 */
            candidacyTypeId: number;
            name: string | null;
            lastName: string | null;
            imageUrl?: string | null;
            /** Format: int32 */
            candidacyTypePosition: number;
        };
        "Domain.Controller.Private.ScrutinySlateCandidacy.GetPaginationResponse.Response": {
            ok?: boolean;
            pagination: components["schemas"]["Domain.API.Interfaces.IPagination"];
            data: components["schemas"]["Domain.Controller.Private.ScrutinySlateCandidacy.GetPaginationResponse.Data"][] | null;
        };
        "Domain.Controller.Private.ScrutinySlateCandidacy.UpdateDto": {
            /** Format: int32 */
            candidacyTypeId?: number | null;
            name?: string | null;
            lastName?: string | null;
        };
        "Domain.Controller.Private.ScrutinySlateCandidacy.UploadImageResponse": {
            imageUrl: string | null;
        };
        "Domain.Controller.Private.Student.AddDto": {
            name: string | null;
            lastName: string | null;
        };
        "Domain.Controller.Private.Student.AddResponse": {
            /** Format: uuid */
            id: string;
        };
        "Domain.Controller.Private.Student.EditDto": {
            name?: string | null;
            lastName?: string | null;
            graduated?: boolean | null;
        };
        "Domain.Controller.Private.Student.GetByIdResponse.Data": {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId?: string | null;
            registrationNumber: string | null;
            name: string | null;
            lastName: string | null;
            graduated: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string | null;
        };
        "Domain.Controller.Private.Student.GetByIdResponse.Response": {
            ok?: boolean;
            data?: components["schemas"]["Domain.Controller.Private.Student.GetByIdResponse.Data"];
        };
        "Domain.Controller.Private.Student.GetPaginationResponse.Data": {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId?: string | null;
            registrationNumber: string | null;
            name: string | null;
            lastName: string | null;
            graduated: boolean;
        };
        "Domain.Controller.Private.Student.GetPaginationResponse.Response": {
            ok?: boolean;
            pagination: components["schemas"]["Domain.API.Interfaces.IPagination"];
            data: components["schemas"]["Domain.Controller.Private.Student.GetPaginationResponse.Data"][] | null;
        };
        "Domain.Controller.Private.User.AddDto": {
            /** Format: int32 */
            userRoleId: number;
            /** Format: uuid */
            studentId?: string | null;
            userName: string | null;
            password: string | null;
            active?: boolean;
        };
        "Domain.Controller.Private.User.AddResponse": {
            /** Format: uuid */
            id: string;
        };
        "Domain.Controller.Private.User.GetByIdResponse.Data": {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            userRoleId: number;
            /** Format: uuid */
            studentId?: string | null;
            userName: string | null;
            active: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string | null;
        };
        "Domain.Controller.Private.User.GetByIdResponse.Response": {
            ok?: boolean;
            data?: components["schemas"]["Domain.Controller.Private.User.GetByIdResponse.Data"];
        };
        "Domain.Controller.Private.User.GetPaginationResponse.Data": {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            userRoleId: number;
            userName: string | null;
            active: boolean;
        };
        "Domain.Controller.Private.User.GetPaginationResponse.Response": {
            ok?: boolean;
            pagination: components["schemas"]["Domain.API.Interfaces.IPagination"];
            data: components["schemas"]["Domain.Controller.Private.User.GetPaginationResponse.Data"][] | null;
        };
        "Domain.Controller.Private.User.UpdateDto": {
            /** Format: int32 */
            userRoleId?: number | null;
            /** Format: uuid */
            studentId?: string | null;
            userName?: string | null;
            password?: string | null;
            active?: boolean | null;
        };
        "Domain.Controller.Public.CandidacyType.GetPaginationResponse.Data": {
            /** Format: int32 */
            id: number;
            name: string | null;
            /** Format: int32 */
            position: number;
        };
        "Domain.Controller.Public.CandidacyType.GetPaginationResponse.Response": {
            ok?: boolean;
            pagination: components["schemas"]["Domain.API.Interfaces.IPagination"];
            data: components["schemas"]["Domain.Controller.Public.CandidacyType.GetPaginationResponse.Data"][] | null;
        };
        "Domain.Controller.Public.Scrutiny.GetByIdResponse.CandidacyData": {
            /** Format: uuid */
            slateId: string;
            /** Format: int32 */
            candidacyTypeId: number;
            name: string | null;
            lastName: string | null;
            imageUrl?: string | null;
        };
        "Domain.Controller.Public.Scrutiny.GetByIdResponse.Data": {
            /** Format: uuid */
            id: string;
            title: string | null;
            description: string | null;
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate: string;
            imageUrl?: string | null;
            slates: components["schemas"]["Domain.Controller.Public.Scrutiny.GetByIdResponse.SlateData"][] | null;
        };
        "Domain.Controller.Public.Scrutiny.GetByIdResponse.Response": {
            ok?: boolean;
            data?: components["schemas"]["Domain.Controller.Public.Scrutiny.GetByIdResponse.Data"];
        };
        "Domain.Controller.Public.Scrutiny.GetByIdResponse.SlateData": {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            scrutinyId: string;
            /** Format: int32 */
            position: number;
            candidacies: components["schemas"]["Domain.Controller.Public.Scrutiny.GetByIdResponse.CandidacyData"][] | null;
        };
        "Domain.Controller.Public.Scrutiny.GetVoteStatusResponse.Data": {
            hasVoted: boolean;
            /** Format: uuid */
            slateId?: string | null;
            /** Format: date-time */
            voteDate?: string | null;
        };
        "Domain.Controller.Public.Scrutiny.GetVoteStatusResponse.Response": {
            ok?: boolean;
            data?: components["schemas"]["Domain.Controller.Public.Scrutiny.GetVoteStatusResponse.Data"];
        };
        "Domain.Controller.Public.Scrutiny.GetPaginationResponse.Data": {
            /** Format: uuid */
            id: string;
            title: string | null;
            description: string | null;
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate: string;
            imageUrl?: string | null;
        };
        "Domain.Controller.Public.Scrutiny.GetPaginationResponse.Response": {
            ok?: boolean;
            pagination: components["schemas"]["Domain.API.Interfaces.IPagination"];
            data: components["schemas"]["Domain.Controller.Public.Scrutiny.GetPaginationResponse.Data"][] | null;
        };
        "Domain.Controller.Public.Scrutiny.PostVoteBody": {
            /** Format: uuid */
            slateId: string;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        "Domain.Models.EScrutinyStatus": 1 | 2 | 3 | 4;
        /**
         * Format: int32
         * @enum {integer}
         */
        "Domain.Models.EUserRole": 1 | 2;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
